#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update -y
sudo apt-get install -y nginx

#Removing the old configuration file
sudo rm /etc/nginx/sites-available/default
sudo rm /etc/nginx/sites-enabled/default

sudo touch /var/www/html/index.html
sudo touch /var/html/page_404.html

#Creating the page_404.html error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/page_404.html

# Create a new configuration file
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.nginx-debian.html;
    server_name _;

    error_page 404 /page_404.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }

}" | sudo tee /etc/nginx/sites-available/redirect

# Create a symbolic link to enable the new configuration
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

sudo chown -R "$USER":"$USER" /var/www/html/index.html

sudo service nginx restart
