#!/usr/bin/env bash
#installing nginx in the on web-01 server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School | sudo tee var/www/html/index.html
sudo service nginx restart
