#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update -y
sudo apt-get install -y nginx

# Remove the default configuration
sudo rm /etc/nginx/sites-available/default
sudo rm /etc/nginx/sites-enabled/default

# Create a new configuration file
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.nginx-debian.html;
    server_name _;

    location /redirect_me {
        return 301 https://www.example.com/new_page;
    }

    location / {
        try_files \$uri \$uri/ = 404;
    }
}' | sudo tee /etc/nginx/sites-available/redirect

# Create a symbolic link to enable the new configuration
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

sudo chown -R "$USER":"$USER" /var/www/html/index.html
sudo service nginx restart
